# Generated by Django 5.1.7 on 2025-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام و نام خانوادگی')),
                ('specialist', models.CharField(blank=True, max_length=200, null=True, verbose_name='تخصص')),
                ('education', models.CharField(blank=True, max_length=200, null=True, verbose_name='تحصیلات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
